name: Build Docker Image

on:
  schedule:
    - cron: '0 1 */5 * *'
  workflow_dispatch:

env:
  APP_NAME: caddy
  DOCKERHUB_REPO: xm798/caddy

jobs:
  Dockerhub:
    name: Build Docker Image and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to ACR
        uses: docker/login-action@v2
        with:
          registry: registry.cn-shanghai.aliyuncs.com
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_TOKEN }}
      - name: Generate App Version
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: |
            linux/arm64/v8
          build-args: |
            APP_NAME=${{ env.APP_NAME }}
            APP_VERSION=${{ env.DATE }}
          tags: |
            registry.cn-shanghai.aliyuncs.com/xm798/caddy:latest
            registry.cn-shanghai.aliyuncs.com/xm798/caddy:${{ env.DATE }}